[package]
name = "mousai"
version = "0.1.0"
authors = ["Dave Patrick <davecruz48@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[dependencies]
log = "0.4.14"
pretty_env_logger = "0.4.0"
gettext-rs = { version = "0.7.0", features = ["gettext-system"] }
once_cell = "1.9.0"
gtk = { version = "0.4.1", package = "gtk4" }
adw = { package = "libadwaita", version = "0.1.0" }
gst = { package = "gstreamer", version = "0.18.0" }
gst_pbutils = { package = "gstreamer-pbutils", version = "0.18.0" }
indexmap = { version = "1.8.0", features = ["serde"] }
reqwest = { version = "0.11.9", features = ["json"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.75"
anyhow = "1.0.52"
base64 = "0.13.0"
pulsectl-rs = "0.3.2"
futures-channel = "0.3.19"
tokio = { version = "1.15.0", features = ["rt", "rt-multi-thread"] }
async-trait = "0.1.52"
rand = "0.8.4"
bytes = "1.1.0"
