[package]
name = "mousai"
version = "0.7.0"
authors = ["Dave Patrick <davecruz48@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[dependencies]
log = "0.4.16"
pretty_env_logger = "0.4.0"
gettext-rs = { version = "0.7.0", features = ["gettext-system"] }
once_cell = "1.10.0"
gtk = { version = "0.4.7", package = "gtk4", features = ["v4_6"] }
adw = { package = "libadwaita", version = "0.1.1" }
gst = { package = "gstreamer", version = "0.18.7" }
gst_pbutils = { package = "gstreamer-pbutils", version = "0.18.7" }
gst_player = { package = "gstreamer-player", version = "0.18.0" }
indexmap = "1.8.1"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
anyhow = "1.0.56"
base64 = "0.13.0"
pulsectl-rs = "0.3.2"
futures-channel = "0.3.21"
async-trait = "0.1.53"
rand = "0.8.5"
thiserror = "1.0.30"
chrono = { version = "0.4.19", features = ["serde"] }
mpris-player = "0.6.1"
typetag = "0.1.8"
percent-encoding = "2.1.0"
soup3 = "0.2.2"
