[package]
name = "mousai"
version = "0.7.5"
authors = ["Dave Patrick Caberto <davecruz48@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[profile.release]
lto = true

[dependencies]
adw = { package = "libadwaita", version = "0.5", features = ["v1_4"] }
anyhow = "1.0"
async-trait = "0.1.58"
futures-channel = "0.3.25"
futures-util = "0.3.25"
fuzzy-matcher = "0.3.7"
gettext-rs = { version = "0.7.0", features = ["gettext-system"] }
gsettings-macro = "0.1.15"
gst = { package = "gstreamer", version = "0.21" }
gst_play = { package = "gstreamer-play", version = "0.21" }
gtk = { version = "0.7", package = "gtk4", features = ["gnome_45"] }
heed = { version = "=0.20.0-alpha.1", features = [
    "serde-bincode",
] } # TODO Remove `=` once https://github.com/meilisearch/heed/pull/203 is merged
indexmap = { version = "2.0", features = ["serde"] }
mpris-player = "0.6.2"
pulse = { package = "libpulse-binding", version = "2.26.0" }
pulse_glib = { package = "libpulse-glib-binding", version = "2.25.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
soup3 = "0.5.0"
strum = { version = "0.25.0", features = ["derive"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"

[dev-dependencies]
tempfile = "3.4.0"
bincode = "1.3"
