[package]
name = "mousai"
version = "0.7.6"
authors = ["Dave Patrick Caberto <davecruz48@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[profile.release]
lto = true

[dependencies]
adw = { package = "libadwaita", version = "0.6", features = ["v1_5"] }
anyhow = "1.0"
async-lock = "3.1"
async-trait = "0.1.58"
futures-channel = "0.3.25"
futures-util = "0.3.25"
fuzzy-matcher = "0.3.7"
gettext-rs = { version = "0.7.0", features = ["gettext-system"] }
gsettings-macro = "0.2.0"
gst = { package = "gstreamer", version = "0.22" }
gst_play = { package = "gstreamer-play", version = "0.22" }
gtk = { version = "0.8", package = "gtk4", features = ["gnome_45"] }
heed = { version = "0.20.0-alpha.6", features = ["serde-bincode"] }
indexmap = { version = "2.0", features = ["serde"] }
mpris-server = "0.7.0"
once_cell = "1.8.0"
pulse = { package = "libpulse-binding", version = "2.26.0" }
pulse_glib = { package = "libpulse-glib-binding", version = "2.25.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
soup3 = "0.6"
strum = { version = "0.26", features = ["derive"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"

[dev-dependencies]
tempfile = "3.4.0"
bincode = "1.3"
