[package]
name = "mousai"
version = "0.7.0"
authors = ["Dave Patrick <davecruz48@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[dependencies]
log = "0.4.17"
pretty_env_logger = "0.4.0"
gettext-rs = { version = "0.7.0", features = ["gettext-system"] }
once_cell = "1.10.0"
soup3 = "0.2.2"
gst = { package = "gstreamer", version = "0.18.8" }
gst_player = { package = "gstreamer-player", version = "0.18.0" }
adw = { package = "libadwaita", version = "0.1.1" }
gtk = { version = "0.4.7", package = "gtk4", features = ["v4_6"] }
indexmap = "1.8.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
anyhow = "1.0.57"
futures-channel = "0.3.21"
async-trait = "0.1.53"
mpris-player = "0.6.1"
typetag = "0.2.0"
gsettings-macro = "0.1.6"
async-channel = "1.6.1"

[dev-dependencies]
serial_test = "0.8.0"
