[package]
name = "mousai"
version = "0.7.8"
authors = ["Dave Patrick Caberto <davecruz48@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[profile.release]
lto = true

[dependencies]
adw = { package = "libadwaita", version = "0.7", features = ["v1_6"] }
anyhow = "1.0"
async-lock = "3.1"
async-trait = "0.1.58"
fuzzy-matcher = "0.3.7"
gettext-rs = { version = "0.7.0", features = ["gettext-system"] }
gsettings-macro = "0.2.0"
gst = { package = "gstreamer", version = "0.23" }
gst_play = { package = "gstreamer-play", version = "0.23" }
gtk = { version = "0.9", package = "gtk4", features = ["gnome_46"] }
heed = { version = "0.20.5", features = ["serde-bincode"] }
indexmap = { version = "2.4", features = ["serde"] }
mpris-server = "0.8.1"
once_cell = "1.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
soup3 = "0.7"
strum = { version = "0.26", features = ["derive"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"

[dev-dependencies]
bincode = "1.3"
futures-util = "0.3"
tempfile = "3.12"
